id: P007888
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01641
  title: ངེས་དོན་དབུ་མ་ཆེན་པོ་ལ་འཁྲུལ་རྟོག་ཉེར་གསུམ་གྱི་འབུར་འཇོམས་པ་ལེགས་བཤད་གསེར་གྱི་ཐོ་བ
  author: ''
  volumes:
    6500ef24727940b698f2d3b0a93dc906:
      image_group_id: I00KG02941
      title: ''
      volume_number: 1
      total_pages: 10
ebook_metadata:
  title: ངེས་དོན་དབུ་མ་ཆེན་པོ་ལ་འཁྲུལ་རྟོག་ཉེར་གསུམ་གྱི་འབུར་འཇོམས་པ་ལེགས་བཤད་གསེར་གྱི་ཐོ་བ
  author: ''
  sku: P007888
  cover: cover.jpg
  layers:
  - pagination
