id: opecha:P007888
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01641
  title: ངེས་དོན་དབུ་མ་ཆེན་པོ་ལ་འཁྲུལ་རྟོག་ཉེར་གསུམ་གྱི་འབུར་འཇོམས་པ་ལེགས་བཤད་གསེར་གྱི་ཐོ་བ
  volume:
    f7732ae984c742eabcda2d560cb27a50:
      image_group_id: I00KG02941
      title: Volume 1 of nges don dbu ma chen po la 'khrul rtog nyer gsum gyi 'bur
        'joms pa legs bshad gser gyi tho ba
      volume_number: 1
      total_pages: 10
  author: ''
ebook_metadata:
  title: ངེས་དོན་དབུ་མ་ཆེན་པོ་ལ་འཁྲུལ་རྟོག་ཉེར་གསུམ་གྱི་འབུར་འཇོམས་པ་ལེགས་བཤད་གསེར་གྱི་ཐོ་བ
  author: ''
  sku: P007888
  cover: cover.jpg
  layers:
  - pagination
