id: I83A819BD
legacy_id: P007888
ocr_import_info:
  bdrc_scan_id: W00KG01641
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T07:35:45'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T11:35:56.660281+00:00'
last_modified: 2022-08-29 19:36:06.214052
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG01641
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG01641
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ངེས་དོན་དབུ་མ་ཆེན་པོ་ལ་འཁྲུལ་རྟོག་ཉེར་གསུམ་གྱི་འབུར་འཇོམས་པ་ལེགས་བཤད་གསེར་གྱི་ཐོ་བ།
  author: འཇམ་མགོན་ཀོང་སྤྲུལ་བློ་གྲོས་མཐའ་ཡས།
statistics:
  ocr_word_mean_confidence_index: 0.6005921498887831
  ocr_word_median_confidence_index: 0.5600000023841858
quality: null
bases:
  I00KG02941:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG02941
      total_pages: 10
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG02941.txt
    statistics:
      ocr_word_median_confidence_index: 0.5600000023841858
      ocr_word_mean_confidence_index: 0.6005921498887831
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
